### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by RyanZuZi** [Milxnor/Universal-Walking-Simulator#33]
All Season 4-5 And Season 8 Patches, re-spawning doesn't work. Add the 5.41 event.

**Comment by Milxnor** [comment]
do you have the paks in the discord in #events for the 12.41 event?

Fixed 7.30 and fixed 4.1 and 4.5 chests (never pushed though).

**Comment by RyanZuZi** [comment]
Yes. This commit (289dd379a43d161a1271ddc0fa52488336299843) works just fine. Everything after it broke the event.

**Comment by RyanZuZi** [comment]
Wait nvm about the event. Didn't realize he pushed a fix. But the other issues still occur. (Until you push it.)

**Comment by RyanZuZi** [comment]
Did you fix re-spawning for those versions?

**Comment by Milxnor** [comment]
no

**Comment by RyanZuZi** [comment]
Ok I'll update my first message.

**Comment by RyanZuZi** [comment]
Is it possible to add a restart button?

**Comment by Milxnor** [comment]
> Is it possible to add a restart button?

done hasn tbeen pushed

**Comment by RyanZuZi** [comment]
ETA?

**Comment by Milxnor** [comment]
i will push everything ive done in a week or something

**Comment by RyanZuZi** [comment]
Hey Milxnor. Hope your doing well. Quick question. Is it possible to add the stage for 12.41?

**Comment by RyanZuZi** [comment]
Milxnor you pushing soon lol github getting mad dry lol
